version: "2"
services:
    app:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./sr:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: my-db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./script:/docker-entrypoint-initdb.d
        networks:
            - default
